# Generated by Django 3.1.7 on 2021-04-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-created',)},
        ),
    ]
